quarkus:
  package:
    type: uber-jar
  http:
    port: 8080
  datasource:
    db-kind: h2
    username: default
    jdbc:
      min-size: 2
      max-size: 8
      url: jdbc:h2:mem:default
    DB2:
      db-kind: h2
      username: db2
      jdbc:
        min-size: 2
        max-size: 8
        url: jdbc:h2:mem:bd2
  log:
    level: DEBUG
  jimmer:
    show-sql: true
    pretty-sql: true
    inline-sql-variables: true
    trigger-type: BOTH
    database-validation:
      mode: NONE
    client:
      ts:
        path: /Code/ts.zip