quarkus:
  application:
    name: quarkus-jimmer-integration-tests
  package:
    type: uber-jar
  http:
    port: 8080
  datasource:
    db-kind: h2
    username: default
    jdbc:
      min-size: 2
      max-size: 8
      url: jdbc:h2:mem:default
    DB2:
      db-kind: h2
      username: db2
      jdbc:
        min-size: 2
        max-size: 8
        url: jdbc:h2:mem:bd2
  log:
    level: DEBUG
  jimmer:
    show-sql: true
    pretty-sql: true
    inline-sql-variables: true
    trigger-type: BOTH
    database-validation:
      mode: NONE
    error-translator:
      disabled: false
      debug-info-supported: true
    client:
      ts:
        path: /Code/ts.zip
      openapi:
        path: /openapi.yml
        ui-path: /openapi.html
        properties:
          info:
            title: Jimmer REST Example(Java)
            description: This is the OpenAPI UI of Quarkus-Jimmer-Extension REST Example (Java)
            version: 0.0.1.CR1
          securities:
            - tenantHeader: [1, 2, 3]
            - oauthHeader: [4, 5, 6]
          components:
            securitySchemes:
              tenantHeader:
                type: apiKey
                name: tenant
                in: HEADER
              oauthHeader:
                type: apiKey
                name: tenant
                in: QUERY