name: Build

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - '*.md'
      - '*.adoc'
      - '*.txt'
      - '.all-contributorsrc'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - '*.md'
      - '*.adoc'
      - '*.txt'
      - '.all-contributorsrc'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
#        os: [windows-latest, macos-latest, ubuntu-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    environment: deploy-setting.xml
    steps:
      - name: Prepare git
        run: git config --global core.autocrlf false
        if: startsWith(matrix.os, 'windows')

      - uses: actions/checkout@v3

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
#          cache: 'maven'

      - name: Set up OSSRH
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
#          cache: 'maven'
          server-id: ossrh
          server-username: ${{ vars.SERVER_OSSRH_USERNAME }}
          server-password: ${{ secrets.SERVER_OSSRH_PASSWORD }}

      - name: Set up CENTRAL
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
#          cache: 'maven'
          server-id: central
          server-username: ${{ vars.SERVER_CENTRAL_USERNAME }}
          server-password: ${{ secrets.SERVER_CENTRAL_PASSWORD }}

      - name: Set up PROFILE
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
#          cache: 'maven'
          profile-id: ossrh
          profile-properties-gpg.executable: ${{ vars.PROFILE_OSSRH_GPG_EXECUTABLE }}
          profile-properties-gpg.passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Build with Maven
        run: mvn -B clean install -Dno-format

      - name: Build with Maven (Native)
        run: mvn -B install -Dnative -Dquarkus.native.container-build -Dnative.surefire.skip
